#!/usr/bin/env bash
#
# Регенерация self-hosted шрифтов из Google Fonts API.
#
# Что делает:
#   1. Запрашивает CSS для Inter / Inter Tight / JetBrains Mono с нужными
#      subset'ами через https://fonts.googleapis.com/css2 (UA = современный
#      Chrome, иначе Google отдаст ttf вместо woff2).
#   2. Извлекает URL'ы woff2 из CSS и складывает файлы в
#      public/fonts/<family>/.
#   3. Переписывает CSS, заменяя https://fonts.gstatic.com/... на
#      локальные /fonts/<family>/<file>, и пишет всё в
#      public/fonts/fonts.css. Этот файл подключает globals.css.
#
# Когда запускать:
#   - При добавлении новых веса/начертания.
#   - При смене подключённого подмножества Unicode.
#   - При апдейте Google Fonts (раз в год хватит — фронт-end-проекты
#     обычно не чувствительны к минорным версиям этих семейств).
#
# Запуск: bash scripts/fetch-fonts.sh
#
# Зависимости: curl, sed, bash 3.2+ (родной macOS).

set -e

UA="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
BASE="$(cd "$(dirname "$0")/.." && pwd)"

dl_font() {
  local key="$1" spec="$2" subset="$3"
  local url="https://fonts.googleapis.com/css2?family=${spec}&subset=${subset}&display=swap"
  echo "== $key =="
  mkdir -p "$BASE/public/fonts/$key"
  local css
  css=$(curl -sS -A "$UA" "$url")
  echo "$css" > "$BASE/public/fonts/$key/_source.css"
  echo "$css" | grep -oE "https://fonts.gstatic.com/[^)]+\.woff2" | sort -u | while read -r u; do
    local fn
    fn=$(basename "$u")
    local out="$BASE/public/fonts/$key/$fn"
    if [ ! -f "$out" ]; then
      curl -sS -A "$UA" -o "$out" "$u" && echo "  + $fn"
    fi
  done
}

dl_font "inter"            "Inter:wght@400;500;600"            "latin,cyrillic"
dl_font "inter-tight"      "Inter+Tight:wght@200;400;500;600"  "latin,cyrillic"
dl_font "jetbrains-mono"   "JetBrains+Mono:wght@400;500"       "latin"
# Onest — основной body-шрифт после Stage 5 Session 2 (типографика).
# Variable font, 4 веса (400/500/600/700) шарят один woff2 на subset.
dl_font "onest"            "Onest:wght@400;500;600;700"        "latin,cyrillic"

# Сборка единого fonts.css с локальными URL'ами.
OUT="$BASE/public/fonts/fonts.css"
{
  echo "/* Self-hosted fonts — auto-generated by scripts/fetch-fonts.sh."
  echo "   Russia blocks fonts.googleapis.com/fonts.gstatic.com; this"
  echo "   replicates the same subset @font-face declarations served"
  echo "   from /fonts/* on our own origin.                              */"
  echo ""
  for key in inter inter-tight jetbrains-mono; do
    sed -E "s|https://fonts.gstatic.com/[^)]+/([^/)]+\.woff2)|/fonts/${key}/\1|g" \
      "$BASE/public/fonts/$key/_source.css"
    echo ""
  done
} > "$OUT"
echo ""
echo "Wrote $OUT  ($(wc -c <"$OUT") bytes)"
echo ""
echo "Если изменился набор файлов — проверь preload в src/app/[locale]/layout.tsx"
echo "и регенерируй <link rel=\"preload\"> для cyrillic-400."
